[toolchain]
channel = "nightly-2025-04-05" # Make sure to update `template/*/rust-toolchain.toml` as well.
components = [
    "rustfmt",
    "clippy",
    # https://github.com/dtolnay/trybuild?tab=readme-ov-file#troubleshooting
    "rust-src",
]
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-musl"]
